Web crawling for cnbc 1st PR
C-KLex/Phraends pull request #14
Opened 2023-08-01 22:14 UTC by Dazeofcitywalk

Summary:
Create the `get_news_from_cnbc` function to crawl articles from http://www.cnbc.com

Details:
· detect link with "PRO" or "CLUB" icon and avoid crawling automatically
· detect video link and avoid crawling automatically
· crawl the accessible articles and store them to txt file

Screenshots:
<img width="975" alt="Screen Shot 2023-08-01 at 6 07 42 PM" src="https://github.com/C-KLex/Phraends/assets/134763676/f5bedc7c-eae8-4209-8cdb-38f1a7f1ae0f">
Take it as example. Only the second article can be crawled, and it is stored in the txt file.

2023-08-03 19:21 UTC, alex308248 commented on Phraends_Flask/Backend/Crawler/Crawler.py
> +        open("the_news_texts.txt", mode="r"),
As we discussed last week, you do not need to write data into a txt file.

2023-08-03 19:23 UTC, alex308248 commented on Phraends_Flask/Backend/Crawler/Crawler.py
> +    for i in range(0, 5):
Could you modified it and make it returning 5 latest articles that is availabe? I believe using while loop will be an easy implementation.

2023-08-03 19:28 UTC, alex308248 requested changes
You'll need to delete the txt file and make the function return 5 articles as a list. As we discussed last week, we will longer use txt file to read and write artilces through crawler and model api. In addition, remeber to pull the lastest version of main branch and fix the conflicts.

2023-08-08 03:42 UTC, Dazeofcitywalk commented
Thanks for reviewing.
For article extension, this website only provides 5 latest articles on it, so I couldn't crawl more articles. 
For txt-list modification, I'm currently debugging, after that I will change the style of return.

2023-08-09 02:24 UTC, alex308248 commented
> Thanks for reviewing. For article extension, this website only provides 5 latest articles on it, so I couldn't crawl more articles. For txt-list modification, I'm currently debugging, after that I will change the style of return.

OK~

2023-08-09 05:50 UTC, YLee2121 commented
have merge conflict, please solve it

2023-08-10 21:46 UTC, Dazeofcitywalk commented
Here is my update:
1. change return style from txt to list
2. test more tickers, and add some try except blocks based on it
3. resolved the merge conflict

Thank you!

2023-08-12 06:00 UTC, alex308248 approved these changes
Approved~

2023-08-12 06:00 UTC, merged