Web crawling 7th PR
C-KLex/Phraends pull request #20
Opened 2023-08-14 04:52 UTC by Weirdojord

# 👉 Summary
### Main in Crawl.py can return links to the articles now.

2023-08-14 19:28 UTC, alex308248 approved these changes
approve

2023-08-14 23:24 UTC, YLee2121 requested changes
This is what I've done in #18. You should merge the main to your branch first and solve the merge conflict. In this case, you remove what I've done in #18.

Please check the #18 again and adjust your code.

Moreover, the order of your get function return is:
link, articles 

Rather than 
article, link

2023-08-15 00:27 UTC, Weirdojord commented
Thanks for the correction, I've just fixed it. Please take a look.

On Mon, Aug 14, 2023 at 7:24 PM YLee2121 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> This is what I've done in #18 <https://github.com/C-KLex/Phraends/pull/18>.
> You should merge the main to your branch first and solve the merge
> conflict. In this case, you remove what I've done in #18
> <https://github.com/C-KLex/Phraends/pull/18>.
>
> Please check the #18 <https://github.com/C-KLex/Phraends/pull/18> again
> and adjust your code.
>
> Moreover, the order of your get function return is:
> link, articles
>
> Rather than
> article, link
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/C-KLex/Phraends/pull/20#pullrequestreview-1577790336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4IP7NBXBEKQMYNTXR5OMZTXVKXTXANCNFSM6AAAAAA3PFD2PQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-08-15 02:50 UTC, YLee2121 approved these changes
approve

2023-08-15 02:50 UTC, merged