frontEnd 2nd PR
C-KLex/Phraends pull request #23
Opened 2023-08-22 19:54 UTC by Dazeofcitywalk

**Summary:**
change frontend return style from "1. summary" to "1. link: summary:"

**Details:**
· delete previous style 
· add new style
· pass the external test and delete test case

**Screenshot:**
<img width="280" alt="截屏2023-08-22 下午3 39 32" src="https://github.com/C-KLex/Phraends/assets/134763676/7164689f-216c-44aa-9630-8523d7caf5cc">

**Others:**
There is still a path problem in importing the backend modules. I couldn't call the `get_5_summary_from_5_articles` function to present outputs without importing those modules.
So I used external test case to make sure the update output style is working (presented in `test.py` from the 1st commit, then deleted it from the 2nd commit).
If the importing problem is solved, I think it will give the return we want.

2023-08-23 04:42 UTC, YLee2121 commented on Phraends.py
> +        return_2list = Phraends_Flask.get_5_summary_from_5_articles()
change to 

```python
links, summaries = Phraends_Flask.get_5_summary_from_5_articles()
```

2023-08-23 04:42 UTC, YLee2121 commented on Phraends.py
> +        for i in range(len(return_2list[0])):
change to 

```python
for link, summary in zip(links, summaries):
...
...
```

2023-08-23 04:43 UTC, YLee2121 requested changes
tiny change required. 

please also revise after my comment.

2023-08-23 05:13 UTC, alex308248 commented
Wondering why couldn't call the `get_5_summary_from_5_articles`. Did you try something like the following?
api_returns = Phraends_Flask.get_5_summary_from_5_articles(ticker)

2023-08-23 05:22 UTC, YLee2121 commented on Phraends.py
> +        return_2list = Phraends_Flask.get_5_summary_from_5_articles()
Also, you need to import this function.

```python
from Phraends_Flask import get_5_summary_from_5_articles
```

2023-08-24 05:43 UTC, YLee2121 approved these changes
@Weirdojord 
Crawler has bug when I use "MMM" as ticker

2023-08-24 05:44 UTC, merged