Web crawling 3rd PR
C-KLex/Phraends pull request #9
Opened 2023-07-19 18:48 UTC by Weirdojord

# 👉 Summary
### Make the investopedia function return 5 links and one txt file containing 5 articles from investopedia.
# 👀 Detail
### Input: ticker name
### Output: 5 links and one txt file containing 5 articles from investopedia.

2023-07-20 04:35 UTC, YLee2121 commented on Phraends_Flask/Backend/Crawler/the_news_texts.txt
@tejkoiejgns 

If you agree with this output format for your convenience, simply only leave an approved comment! Then, I will know you've had an agreement with @Weirdojord.

2023-07-20 04:38 UTC, YLee2121 commented on Phraends_Flask/Backend/Crawler/Crawler.py
@Weirdojord 

I wanted you to write the function comment for `get_news_from_investopedia based on the guideline! Please make sure to write it clearly.

2023-07-20 04:39 UTC, YLee2121 requested changes
Request changes

2023-07-20 16:29 UTC, Weirdojord commented
Ok no problem!

On Thu, Jul 20, 2023 at 12:39 AM YLee2121 ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On Phraends_Flask/Backend/Crawler/Crawler.py
> <https://github.com/C-KLex/Phraends/pull/9#discussion_r1268924496>:
>
> @Weirdojord <https://github.com/Weirdojord>
>
> I wanted you to write the function comment for `get_news_from_investopedia
> based on the guideline! Please make sure to write it clearly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/C-KLex/Phraends/pull/9#pullrequestreview-1538413362>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4IP7NCZTCV5SQ7N2TF3OJLXRCY6HANCNFSM6AAAAAA2QK2FBY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-23 22:52 UTC, tejkoiejgns commented on Phraends_Flask/Backend/Crawler/the_news_texts.txt
agree!

2023-07-26 14:48 UTC, YLee2121 approved these changes
Approve

2023-07-26 14:48 UTC, merged